import React from "react";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout";
import { Head, Link, useForm } from "@inertiajs/react";
import { useLang } from "@/Contexts/LanguageContext";
import {
    Save,
    Calculator,
    ChevronRight,
    Home,
} from "lucide-react";
import InputLabel from "@/Components/InputLabel";
import InputError from "@/Components/InputError";
import PrimaryButton from "@/Components/PrimaryButton";

export default function Accounting({ settings, accounts }) {
    const { lang } = useLang();

    const { data, setData, post, processing, errors } = useForm({
        invoice_default_revenue_account: settings?.invoice_default_revenue_account || "",
        invoice_default_ar_account: settings?.invoice_default_ar_account || "",
        invoice_default_cash_account: settings?.invoice_default_cash_account || "",
        invoice_default_bank_account: settings?.invoice_default_bank_account || "",
        invoice_allow_override_revenue: settings?.invoice_allow_override_revenue === "1",
        invoice_auto_post: settings?.invoice_auto_post === "1",
    });

    const submit = (e) => {
        e.preventDefault();
        post(route("settings.accounting.store"));
    };

    const breadcrumbs = (
        <div className="flex items-center gap-2 text-[12px] text-text-muted">
            <Home className="h-3.5 w-3.5" />
            <ChevronRight
                className={`h-3.5 w-3.5 ${lang === "ar" ? "rotate-180" : ""}`}
            />
            <Link
                href={route("settings.index")}
                className="hover:text-primary transition-colors"
            >
                {lang === "ar" ? "الإعدادات" : "Settings"}
            </Link>
            <ChevronRight
                className={`h-3.5 w-3.5 ${lang === "ar" ? "rotate-180" : ""}`}
            />
            <span className="text-primary font-medium">
                {lang === "ar" ? "إعدادات المالية للفواتير" : "Invoice Accounting Settings"}
            </span>
        </div>
    );

    return (
        <AuthenticatedLayout header={breadcrumbs}>
            <Head
                title={
                    lang === "ar"
                        ? "إعدادات المالية للفواتير"
                        : "Invoice Accounting Settings"
                }
            />

            <div className="pb-4" dir={lang === "ar" ? "rtl" : "ltr"}>
                <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 space-y-4 mt-4">
                    {/* Header Box */}
                    <div className="flex items-center justify-between border border-border rounded-xl px-4 py-3 bg-surface shadow-sm">
                        <div className="flex items-center gap-3">
                            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary">
                                <Calculator className="h-5 w-5" />
                            </div>
                            <div>
                                <h1 className="text-xl font-bold text-text leading-tight">
                                    {lang === "ar"
                                        ? "إعدادات الربط المالي للفواتير"
                                        : "Invoice Accounting Settings"}
                                </h1>
                                <p className="text-[12px] text-text-muted mt-0.5">
                                    {lang === "ar"
                                        ? "تحديد الحسابات الافتراضية للقيود اليومية الناتجة عن الفواتير وعمليات الدفع."
                                        : "Set default accounts for journal entries generated by invoices and payments."}
                                </p>
                            </div>
                        </div>
                    </div>

                    {/* Content Box */}
                    <div className="rounded-xl border border-border bg-surface shadow-sm overflow-hidden p-6">
                        <form onSubmit={submit} className="space-y-6">
                            
                            <div className="border-b border-border pb-3 mb-4">
                                <h2 className="text-[14px] font-bold text-text">
                                    {lang === "ar"
                                        ? "الحسابات الافتراضية للفواتير"
                                        : "Default Invoice Accounts"}
                                </h2>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                {/* Revenue Account */}
                                <div>
                                    <InputLabel value={lang === "ar" ? "حساب الإيرادات الافتراضي" : "Default Revenue Account"} />
                                    <select
                                        className="mt-1 block w-full rounded-md border border-border bg-surface text-sm py-2 px-3 focus:border-primary focus:ring-primary shadow-sm"
                                        value={data.invoice_default_revenue_account}
                                        onChange={(e) => setData("invoice_default_revenue_account", e.target.value)}
                                    >
                                        <option value="">{lang === "ar" ? "اختر حساب الإيرادات..." : "Select Revenue Account..."}</option>
                                        {accounts.filter(a => a.type === 'revenue' || a.type === 'income').map(acc => (
                                            <option key={acc.id} value={acc.id}>
                                                {acc.code} - {lang === 'ar' ? acc.name_ar : acc.name_en}
                                            </option>
                                        ))}
                                        {accounts.filter(a => a.type !== 'revenue' && a.type !== 'income').map(acc => (
                                            <option key={acc.id} value={acc.id}>
                                                {acc.code} - {lang === 'ar' ? acc.name_ar : acc.name_en} ({acc.type})
                                            </option>
                                        ))}
                                    </select>
                                    <InputError message={errors.invoice_default_revenue_account} className="mt-1" />
                                </div>

                                {/* Accounts Receivable (AR) Account */}
                                <div>
                                    <InputLabel value={lang === "ar" ? "حساب العملاء الافتراضي (الذمم المدينة)" : "Default AR Account (Accounts Receivable)"} />
                                    <select
                                        className="mt-1 block w-full rounded-md border border-border bg-surface text-sm py-2 px-3 focus:border-primary focus:ring-primary shadow-sm"
                                        value={data.invoice_default_ar_account}
                                        onChange={(e) => setData("invoice_default_ar_account", e.target.value)}
                                    >
                                        <option value="">{lang === "ar" ? "اختر حساب العملاء..." : "Select AR Account..."}</option>
                                        {accounts.map(acc => (
                                            <option key={acc.id} value={acc.id}>
                                                {acc.code} - {lang === 'ar' ? acc.name_ar : acc.name_en} ({acc.type})
                                            </option>
                                        ))}
                                    </select>
                                    <InputError message={errors.invoice_default_ar_account} className="mt-1" />
                                </div>

                                {/* Cash Account */}
                                <div>
                                    <InputLabel value={lang === "ar" ? "حساب الصندوق الافتراضي (نقد)" : "Default Cash Account"} />
                                    <select
                                        className="mt-1 block w-full rounded-md border border-border bg-surface text-sm py-2 px-3 focus:border-primary focus:ring-primary shadow-sm"
                                        value={data.invoice_default_cash_account}
                                        onChange={(e) => setData("invoice_default_cash_account", e.target.value)}
                                    >
                                        <option value="">{lang === "ar" ? "اختر حساب الصندوق..." : "Select Cash Account..."}</option>
                                        {accounts.map(acc => (
                                            <option key={acc.id} value={acc.id}>
                                                {acc.code} - {lang === 'ar' ? acc.name_ar : acc.name_en} ({acc.type})
                                            </option>
                                        ))}
                                    </select>
                                    <InputError message={errors.invoice_default_cash_account} className="mt-1" />
                                </div>

                                {/* Bank Account */}
                                <div>
                                    <InputLabel value={lang === "ar" ? "حساب البنك الافتراضي (حوالة/بطاقة)" : "Default Bank Account"} />
                                    <select
                                        className="mt-1 block w-full rounded-md border border-border bg-surface text-sm py-2 px-3 focus:border-primary focus:ring-primary shadow-sm"
                                        value={data.invoice_default_bank_account}
                                        onChange={(e) => setData("invoice_default_bank_account", e.target.value)}
                                    >
                                        <option value="">{lang === "ar" ? "اختر حساب البنك..." : "Select Bank Account..."}</option>
                                        {accounts.map(acc => (
                                            <option key={acc.id} value={acc.id}>
                                                {acc.code} - {lang === 'ar' ? acc.name_ar : acc.name_en} ({acc.type})
                                            </option>
                                        ))}
                                    </select>
                                    <InputError message={errors.invoice_default_bank_account} className="mt-1" />
                                </div>
                            </div>

                            <div className="border-b border-border pb-3 mb-4 mt-8">
                                <h2 className="text-[14px] font-bold text-text">
                                    {lang === "ar"
                                        ? "خيارات إضافية"
                                        : "Additional Options"}
                                </h2>
                            </div>

                            <div className="flex flex-col gap-4">
                                <label className="flex items-center gap-3 cursor-pointer">
                                    <input
                                        type="checkbox"
                                        className="rounded border-border text-primary shadow-sm focus:ring-primary"
                                        checked={data.invoice_allow_override_revenue}
                                        onChange={(e) => setData("invoice_allow_override_revenue", e.target.checked)}
                                    />
                                    <div>
                                        <div className="text-sm font-medium text-text">
                                            {lang === "ar" ? "السماح بتغيير حساب الإيرادات عند إنشاء الفاتورة" : "Allow overriding revenue account during invoice creation"}
                                        </div>
                                    </div>
                                </label>

                                <label className="flex items-center gap-3 cursor-pointer">
                                    <input
                                        type="checkbox"
                                        className="rounded border-border text-primary shadow-sm focus:ring-primary"
                                        checked={data.invoice_auto_post}
                                        onChange={(e) => setData("invoice_auto_post", e.target.checked)}
                                    />
                                    <div>
                                        <div className="text-sm font-medium text-text">
                                            {lang === "ar" ? "ترحيل القيود تلقائياً عند اعتماد الفاتورة/الدفعة" : "Auto-post journal entries on invoice/payment approval"}
                                        </div>
                                    </div>
                                </label>
                            </div>

                            <div className="pt-4 border-t border-border flex justify-end gap-2 mt-6">
                                <PrimaryButton disabled={processing} className="px-6 py-2 shadow-sm">
                                    <Save className="h-4 w-4 me-2" />
                                    <span>{lang === "ar" ? "حفظ الإعدادات" : "Save Settings"}</span>
                                </PrimaryButton>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
